name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: yarn build-main
        run: ls -la
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/main

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: build.tgz
